# -*- coding: utf-8 -*-
"""V4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EkVGLkhe_U9V-EZXM7N6wzAbi0cL3Rii

# European Energy Load Analysis

End-to-end pipeline: load → feature engineering → hourly resampling → holiday flags → geographic clustering.
"""

import os
import warnings
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy import signal
from scipy.signal import detrend, correlate, correlation_lags
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
import holidays
from sklearn.preprocessing import MinMaxScaler
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tqdm import tqdm
warnings.filterwarnings('ignore')
print('Libraries loaded.')

"""## Google Drive"""

# Commented out IPython magic to ensure Python compatibility.
from google.colab import drive
drive.mount('/content/drive')
# %cd '/content/drive/MyDrive/Colab Notebooks/F_Thesis'

"""## Configuration"""

OUTPUT_DIR = "energy_load_analysis_plots_final"
ORIGINAL_DATA = "CombinedEurope_clean_header.csv"
OPSD_DATA = "time_series_60min.csv"
WEATHER_DATA = "weather_data.csv"
OUTPUT_FILE = "Final_All_Countries_Dataset_Enhanced.csv"
ENERGY_PATH = "CombinedEurope_clean_header.csv"
OPSD_PATH = "time_series_60min.csv"
WEATHER_PATH = "weather_data.csv"
SAMPLE_MODE = False
if not os.path.exists(OUTPUT_DIR):
    os.makedirs(OUTPUT_DIR)

"""## Data Loading"""

def validate_file_exists(path, label=''):
    if not os.path.exists(path):
        print(f'  [ERROR] {label} not found: {path}')
        return False
    if os.path.getsize(path) == 0:
        print(f'  [ERROR] {label} is empty: {path}')
        return False
    return True


def load_csv_safely(path, nrows=None):
    print(f'  Loading: {os.path.basename(path)}')
    for i, kwargs in enumerate([
        dict(low_memory=False, nrows=nrows),
        dict(nrows=nrows),
        dict(engine='python', nrows=nrows),
        dict(encoding='latin1', nrows=nrows),
        dict(encoding='utf-8', nrows=nrows),
    ], 1):
        try:
            df = pd.read_csv(path, **kwargs)
            print(f'    OK (strategy {i}) — {len(df):,} rows, {len(df.columns)} cols')
            return df
        except Exception:
            continue
    raise ValueError(f'Could not load: {path}')


def get_country_codes(columns):
    codes = set()
    for col in columns:
        parts = col.split('_')
        if len(parts) >= 2 and len(parts[0]) == 2 and parts[0].isalpha() and parts[0].isupper():
            codes.add(parts[0])
    return sorted(codes)

"""## Column Mapping"""

def build_column_mapping(df_opsd, df_weather, all_countries):
    patterns = {
        'load':        ['_load_actual_entsoe_transparency', '_load'],
        'solar':       ['_solar_generation_actual', '_solar'],
        'wind_power':  ['_wind_generation_actual', '_wind_onshore_generation_actual', '_wind'],
        'temperature': ['_temperature'],
        'wind_speed':  ['_wind_speed', '_wind_velocity'],
    }
    mapping, country_features = {}, {}
    for country in all_countries:
        for feature, candidates in patterns.items():
            for suffix in candidates:
                col = f'{country}{suffix}'
                if col in df_opsd.columns or col in df_weather.columns:
                    mapping[col] = f'{country}_{feature}'
                    country_features.setdefault(country, set()).add(feature)
                    break
    return mapping, country_features


def get_countries_with_wind(country_features, all_countries):
    return [c for c in all_countries if 'wind_power' in country_features.get(c, set())]

"""## Feature Extraction"""

def extract_all_features(df, mapping, country, opsd_idx, weather_idx):
    for feature in ['load', 'temperature', 'solar', 'wind_power']:
        src_cols = [k for k, v in mapping.items() if v == f'{country}_{feature}']
        if not src_cols:
            continue
        src = src_cols[0]
        source = opsd_idx if src in opsd_idx.columns else weather_idx if src in weather_idx.columns else None
        if source is not None:
            df[f'{country}_{feature}'] = source[src].reindex(df.index).fillna(0).values

    ws_cols = [k for k, v in mapping.items() if v == f'{country}_wind_speed']
    if ws_cols and ws_cols[0] in weather_idx.columns:
        df[f'{country}_wind_speed_m_s']  = weather_idx[ws_cols[0]].reindex(df.index).fillna(0).values
        df[f'{country}_wind_speed_km_h'] = df[f'{country}_wind_speed_m_s'] * 3.6
    return df

"""## Physics-Based Features"""

def _ts(df, field):
    if 'utc_timestamp' in df.columns:
        return getattr(df['utc_timestamp'].dt, field)
    return pd.Series(getattr(df.index, field), index=df.index)


def apply_physics_features(df, countries):
    for country in countries:
        tc = f'{country}_temperature'
        if tc not in df.columns:
            continue
        temp = df[tc].ffill().bfill()

        df[f'{country}_hdd'] = np.maximum(0, 18 - temp)
        df[f'{country}_cdd'] = np.maximum(0, temp - 22)

        month = _ts(df, 'month')
        sf = np.where(month.isin([6,7,8]), 0.85, np.where(month.isin([12,1,2]), 0.70, 0.75))
        bd = np.where(temp > 20, temp*0.10, np.where(temp > 0, temp*0.15, temp*0.20))
        dp = temp - bd * sf
        df[f'{country}_dew_point'] = dp.clip(lower=temp-12, upper=temp-1)

        eff  = np.where(temp < -10, 0.85, np.where(temp < 0, 0.92, 0.98))
        hour = _ts(df, 'hour')
        tf   = np.where(hour.isin(set(range(0,6)) | set(range(18,24))), 1.25, 1.0)
        df[f'{country}_heating_intensity'] = df[f'{country}_hdd'] * eff * tf

        ce   = np.where(temp > 35, 0.80, np.where(temp > 28, 0.90, 0.95))
        biz  = np.where(hour.isin(range(9,18)), 1.35, np.where(hour.isin([7,8,18,19]), 1.15, 0.85))
        wknd = np.where(_ts(df, 'weekday') >= 5, 1.20, 1.0)
        df[f'{country}_cooling_intensity'] = df[f'{country}_cdd'] * ce * biz * wknd

        target = f'{country}_wind_speed_km_h'
        if target not in df.columns:
            for col in [f'{country}_wind', f'{country}_wind_power', f'{country}_wind_generation']:
                if col in df.columns:
                    df[target] = 10 * np.cbrt(df[col].fillna(0) / 1000 + 1)
                    break
            else:
                df[target] = 0.0

    print(f'  Physics features applied for {len(countries)} countries.')
    return df

"""## Data Cleaning & Column Organisation"""

def clean_and_optimize(df):
    if 'utc_timestamp' in df.columns:
        df = df[df['utc_timestamp'].dt.year.between(2015, 2020)].copy()
        print(f'  Filtered to {len(df):,} rows (2015–2020)')
    num = df.select_dtypes(include=[np.number]).columns
    df[num] = df[num].ffill().bfill().fillna(0)
    n0 = len(df)
    df = df.drop_duplicates(subset=['utc_timestamp'] if 'utc_timestamp' in df.columns else None)
    if len(df) < n0:
        print(f'  Removed {n0 - len(df)} duplicates')
    for col in df.select_dtypes('float64').columns:
        df[col] = df[col].astype(np.float32)
    return df

def organize_columns_by_country(df_final, countries_with_wind):
    print("\n Organizing columns by country in specified order...")

    wind_cols = [col for col in df_final.columns if col.endswith('_wind') and not col.endswith('_wind_speed')]
    if wind_cols:
        rename_dict = {col: col.replace('_wind', '_wind_power_MW') for col in wind_cols}
        df_final = df_final.rename(columns=rename_dict)
        print(f"   Renamed {len(rename_dict)} wind columns: _wind → _wind_power_MW")

    wind_potential_cols = [col for col in df_final.columns if col.endswith('_wind_potential')]
    if wind_potential_cols:
        df_final = df_final.drop(columns=wind_potential_cols)
        print(f"   Dropped {len(wind_potential_cols)} wind_potential columns")

    ordered_cols = []

    for ts_col in ['utc_timestamp', 'cet_cest_timestamp']:
        if ts_col in df_final.columns:
            ordered_cols.append(ts_col)

    feature_order = [
        '_load', '_temperature', '_solar', '_dew_point',
        '_hdd', '_cdd', '_heating_intensity', '_cooling_intensity', '_wind_power', '_wind_speed_km_h', '_wind_power_MW'

    ]

    for country in sorted(countries_with_wind):
        for feature in feature_order:
            col_name = f"{country}{feature}"
            if col_name in df_final.columns:
                ordered_cols.append(col_name)

    remaining_cols = [col for col in df_final.columns if col not in ordered_cols]
    if remaining_cols:
        ordered_cols.extend(remaining_cols)

    return df_final[ordered_cols]

"""## Main Pipeline"""

def build_base_dataset(opsd_path, weather_path, output_file, sample_mode=False):
    print('[STEP 1] Validating files...')
    for path, label in [(opsd_path,'OPSD'),(weather_path,'Weather')]:
        if not validate_file_exists(path, label):
            return None, []

    nrows   = 10_000 if sample_mode else None
    df_opsd = load_csv_safely(opsd_path,    nrows=nrows)
    df_weat = load_csv_safely(weather_path, nrows=nrows)

    print('[STEP 2] Parsing timestamps...')
    for df in (df_opsd, df_weat):
        if 'utc_timestamp' in df.columns:
            df['utc_timestamp'] = pd.to_datetime(df['utc_timestamp'], utc=True, errors='coerce')

    print('[STEP 3] Mapping columns...')
    all_countries = sorted(set(get_country_codes(df_opsd.columns)) | set(get_country_codes(df_weat.columns)))
    mapping, country_features = build_column_mapping(df_opsd, df_weat, all_countries)
    countries = get_countries_with_wind(country_features, all_countries)
    print(f'  {len(countries)} countries with wind: {countries}')

    print('[STEP 4] Aligning on OPSD timestamp grid...')
    opsd_idx = df_opsd.set_index('utc_timestamp')
    weat_idx = df_weat.set_index('utc_timestamp').reindex(opsd_idx.index).fillna(0)

    print('[STEP 5] Assembling dataset...')
    df = pd.DataFrame(index=opsd_idx.index)
    if 'cet_cest_timestamp' in df_opsd.columns:
        df['cet_cest_timestamp'] = df_opsd['cet_cest_timestamp'].values
    for country in countries:
        df = extract_all_features(df, mapping, country, opsd_idx, weat_idx)
    df = df.reset_index().rename(columns={'index':'utc_timestamp'})
    print(f'  Assembled {len(df):,} rows x {len(df.columns)} cols')

    print('[STEP 6] Cleaning...')
    df = clean_and_optimize(df)

    print('[STEP 7] Applying physics features...')
    df = apply_physics_features(df, countries)

    print('[STEP 8] Organising columns...')
    df = organize_columns_by_country(df, countries)

    print('[STEP 9] Saving...')
    df.to_csv(output_file, index=False)
    mb = os.path.getsize(output_file) / 1_048_576
    print(f'  Saved: {output_file}  ({mb:.2f} MB)')

    print(f'\nDataset shape: {df.shape}')
    return df, countries

"""## Run Base Pipeline"""

df_final, countries_with_wind = build_base_dataset(
    OPSD_DATA, WEATHER_DATA, OUTPUT_FILE, sample_mode=SAMPLE_MODE
)

df_final.head()

"""## Hourly Feature Engineering"""

def build_hourly_dataset(df_final, countries):
    df = df_final.copy()
    if 'utc_timestamp' in df.columns:
        df.index = pd.to_datetime(df['utc_timestamp'])
        df = df.drop(columns=['utc_timestamp','cet_cest_timestamp'], errors='ignore')
    df = df.select_dtypes(include=[np.number]).resample('h').mean().ffill().bfill()

    df['hour_sin']  = np.sin(2*np.pi*df.index.hour      / 24)
    df['hour_cos']  = np.cos(2*np.pi*df.index.hour      / 24)
    df['dow_sin']   = np.sin(2*np.pi*df.index.dayofweek / 7)
    df['dow_cos']   = np.cos(2*np.pi*df.index.dayofweek / 7)
    df['month_sin'] = np.sin(2*np.pi*df.index.month     / 12)
    df['month_cos'] = np.cos(2*np.pi*df.index.month     / 12)

    for country in countries:
        col = f'{country}_load'
        if col not in df.columns:
            continue
        s = df[col]
        df[f'{country}_load_lag_1h']   = s.shift(1)
        df[f'{country}_load_lag_24h']  = s.shift(24)
        df[f'{country}_load_lag_168h'] = s.shift(168)
        df[f'{country}_load_roll_24h'] = s.rolling(24,  min_periods=1).mean()
        df[f'{country}_load_roll_7d']  = s.rolling(168, min_periods=1).mean()

    df['hour']        = df.index.hour
    df['day_of_week'] = df.index.dayofweek
    df['is_weekend']  = (df.index.dayofweek >= 5).astype(np.int8)
    df['month']       = df.index.month
    df['season']      = df['month'].map({
        12:'winter',1:'winter',2:'winter',
        3:'spring', 4:'spring',5:'spring',
        6:'summer', 7:'summer',8:'summer',
        9:'autumn',10:'autumn',11:'autumn',
    })
    df = df.fillna(0)

    print(f'Hourly dataset shape: {df.shape}')
    return df

"""## Build Hourly Dataset"""

countries_with_wind = sorted({
    col.split('_')[0] for col in df_final.columns
    if col.endswith('_load') and len(col.split('_')[0]) == 2
})

df_hourly = build_hourly_dataset(df_final, countries_with_wind)

print('Season distribution:')
print(df_hourly['season'].value_counts().to_string())
df_hourly.head()

"""## Holiday Features"""

def add_holiday_features(df, countries):
    if not isinstance(df.index, pd.DatetimeIndex):
        df.index = pd.to_datetime(df.index)

    years = list(range(df.index.year.min(), df.index.year.max() + 1))
    all_holiday_dates = set()

    for country in countries:
        try:
            ch = holidays.country_holidays(country, years=years)
            all_holiday_dates.update(ch.keys())
        except Exception:
            pass

    date_series = pd.Series(df.index.date, index=df.index)
    df['is_holiday'] = date_series.map(lambda d: 1 if d in all_holiday_dates else 0).astype(int)

    total = len(df)
    n_hol = df['is_holiday'].sum()
    print(f"  Holiday hours: {n_hol:,}  ({100*n_hol/total:.1f}%)")
    return df

df_hourly = add_holiday_features(df_hourly, countries_with_wind)
print(df_hourly['is_holiday'].value_counts().to_string())
df_hourly.head()

plt.style.use('seaborn-v0_8-whitegrid')

def plot_yearly_monthly_scatter(df_hourly, countries, n_cols=6):
    """
    Year-over-year monthly mean load scatter plots for every country.
    Each country gets one subplot with dots colored by year.
    """
    # Filter to countries with load data
    valid_countries = [c for c in countries if f'{c}_load' in df_hourly.columns]
    n_countries = len(valid_countries)

    if n_countries == 0:
        print("No valid countries found")
        return

    n_rows = (n_countries + n_cols - 1) // n_cols

    fig, axes = plt.subplots(n_rows, n_cols, figsize=(n_cols * 3.5, n_rows * 3))
    axes = axes.flatten()

    # Years and colors
    years = [2015, 2016, 2017, 2018, 2019, 2020]
    colors = ['#E63946', '#219EBC', '#FFB703', '#8338EC', '#06D6A0', '#FB8507']

    for i, country in enumerate(valid_countries):
        ax = axes[i]
        load_col = f'{country}_load'

        # Calculate monthly means for each year
        for year, color in zip(years, colors):
            year_data = df_hourly[load_col][df_hourly[load_col].index.year == year]

            if len(year_data) > 0:
                monthly_means = year_data.resample('ME').mean()
                months = monthly_means.index.month

                ax.scatter(months, monthly_means.values,
                          color=color, s=30, alpha=0.8,
                          edgecolors='black', linewidth=0.5,
                          label=str(year), zorder=3)

        ax.set_title(f'{country}', fontsize=11, fontweight='bold')
        ax.set_xticks(range(1, 13))
        ax.set_xticklabels(['J','F','M','A','M','J','J','A','S','O','N','D'], fontsize=7)
        ax.set_xlim(0.5, 12.5)
        ax.grid(True, alpha=0.3, linestyle='--')

        # Only show y-label on leftmost plots
        if i % n_cols == 0:
            ax.set_ylabel('Mean Load (MW)', fontsize=9)

        # Only show x-label on bottom plots
        if i >= n_countries - n_cols:
            ax.set_xlabel('Month', fontsize=9)

    # Remove empty subplots
    for j in range(i + 1, len(axes)):
        axes[j].set_visible(False)

    # Single legend at the bottom
    handles, labels = axes[0].get_legend_handles_labels()
    fig.legend(handles, labels, loc='lower center',
              fontsize=10, ncol=len(years),
              bbox_to_anchor=(0.5, -0.02), frameon=True)

    fig.suptitle('Year-over-Year Monthly Mean Load\n(2015–2020)',
                fontsize=16, fontweight='bold', y=1.01)

    plt.tight_layout()
    plt.show()

print("=" * 60)
print("YEAR-OVER-YEAR MONTHLY MEAN LOAD — ALL COUNTRIES")
print("=" * 60)

# Compact version (6 columns)
print("\n1/2: Compact Grid (6 columns)...")
plot_yearly_monthly_scatter(df_hourly, countries_with_wind, n_cols=6)

"""#Cross Correlation Heatmap"""

def find_max_lag_correlation_scipy(signal1, signal2, max_lag=48):
    """
    Find maximum cross-correlation between two signals within a lag window.
    """
    # Convert to numpy arrays if they are pandas Series
    if hasattr(signal1, 'values'):
        signal1 = signal1.values
    if hasattr(signal2, 'values'):
        signal2 = signal2.values

    if len(signal1) < 20 or len(signal2) < 20:
        return 0.0, 0, None

    # Standardize signals
    s1 = (signal1 - np.mean(signal1)) / (np.std(signal1) + 1e-8)
    s2 = (signal2 - np.mean(signal2)) / (np.std(signal2) + 1e-8)

    # Compute cross-correlation using FFT
    cross_corr = correlate(s1, s2, mode='full', method='fft')
    lags = correlation_lags(len(s1), len(s2), mode='full')

    # Normalize by number of overlapping samples
    lengths = np.minimum(np.arange(1, len(cross_corr) + 1),
                        np.arange(len(cross_corr), 0, -1))
    norm_corr = cross_corr / (lengths + 1e-8)

    # Mask lags within desired range
    mask = np.abs(lags) <= min(max_lag, len(s1) // 4)

    if np.any(mask):
        valid_corr = norm_corr[mask]
        valid_lags = lags[mask]

        # Find maximum absolute correlation
        max_idx = np.argmax(np.abs(valid_corr))
        max_corr = valid_corr[max_idx]
        lag_at_max = valid_lags[max_idx]

        return max_corr, lag_at_max, valid_corr
    else:
        return 0.0, 0, None

def _compute_lagged_correlation(load_signal, feature_signal, max_lag=48):
    """
    Helper function to compute the best cross-correlation between load and a feature,
    considering time lags and detrending.
    Accepts both numpy arrays and pandas Series.
    """
    # Convert to numpy arrays if needed
    if hasattr(load_signal, 'values'):
        load_signal = load_signal.values
    if hasattr(feature_signal, 'values'):
        feature_signal = feature_signal.values

    # Clean data: remove NaN and infinite values
    mask = np.isfinite(load_signal) & np.isfinite(feature_signal)
    v_load = load_signal[mask]
    v_feat = feature_signal[mask]

    if len(v_load) < 20:
        return 0.0

    try:
        # Compute correlation with raw data
        c1, _, _ = find_max_lag_correlation_scipy(v_load, v_feat, max_lag=max_lag)

        # Compute correlation with detrended data (removes long-term trends)
        c2, _, _ = find_max_lag_correlation_scipy(detrend(v_load), detrend(v_feat), max_lag=max_lag)

        # Return the stronger correlation
        return c1 if abs(c1) > abs(c2) else c2
    except Exception as e:
        return 0.0

def compute_row_metrics(df: pd.DataFrame, country_code: str) -> dict:
    """
    Computes correlation metrics between electricity load and various features for a specific country.
    """
    load_col = f'{country_code}_load'

    if load_col not in df.columns:
        return None

    load_series = df[load_col].dropna()
    results = {}

    # 1. Weather Features (Lag-Optimized Cross-Correlation)
    weather_features = {
        'solar': 'Solar',
        'wind_power': 'Wind',
        'temperature': 'Temperature',
        'hdd': 'HDD',
        'cdd': 'CDD',
        'dew_point': 'Dew_Point',
        'wind_speed_km_h': 'Wind_Speed',
        'heating_intensity': 'Heating_Intensity',
        'cooling_intensity': 'Cooling_Intensity'
    }

    for key, display_name in weather_features.items():
        feature_col = f"{country_code}_{key}"
        if feature_col in df.columns:
            feature_series = df[feature_col].dropna()
            common_idx = load_series.index.intersection(feature_series.index)
            if len(common_idx) > 20:
                results[display_name] = _compute_lagged_correlation(
                    load_series.loc[common_idx],
                    feature_series.loc[common_idx]
                )
            else:
                results[display_name] = 0.0
        else:
            results[display_name] = 0.0

    # 2. Lag & Rolling Features (Standard Pearson Correlation)
    lag_roll_mapping = [
        (f'{country_code}_load_lag_1h', 'Load_Lag_1h'),
        (f'{country_code}_load_lag_24h', 'Load_Lag_24h'),
        (f'{country_code}_load_lag_168h', 'Load_Lag_168h'),
        (f'{country_code}_load_roll_24h', 'Load_Roll_24h'),
        (f'{country_code}_load_roll_7d', 'Load_Roll_7d')
    ]

    for col_name, display_name in lag_roll_mapping:
        if col_name in df.columns:
            corr_val = load_series.corr(df[col_name])
            results[display_name] = round(corr_val, 4) if pd.notna(corr_val) else 0.0
        else:
            results[display_name] = 0.0

    # 3. Temporal Features (Standard Pearson Correlation)
    temporal_features = {
        'hour': 'Hour',
        'day_of_week': 'Day_of_Week',
        'is_weekend': 'Is_Weekend',
        'month': 'Month',
        'is_holiday': 'Is_Holiday'
    }

    for col_name, display_name in temporal_features.items():
        if col_name in df.columns:
            corr_val = load_series.corr(df[col_name])
            results[display_name] = round(corr_val, 4) if pd.notna(corr_val) else 0.0
        else:
            results[display_name] = 0.0

    # 4. Season (Categorical to Numeric)
    if 'season' in df.columns:
        season_map = {'winter': 1, 'spring': 2, 'summer': 3, 'autumn': 4}
        season_numeric = df['season'].map(season_map)
        corr_val = load_series.corr(season_numeric)
        results['Season'] = round(corr_val, 4) if pd.notna(corr_val) else 0.0
    else:
        results['Season'] = 0.0

    return results

def compute_cross_correlation_matrix(df: pd.DataFrame, countries: list) -> pd.DataFrame:
    """
    Computes a cross-correlation matrix for all countries in the dataset.
    """
    print(f"Computing correlations for {len(countries)} countries...")

    # Compute correlations for each country
    results = []
    for country in tqdm(countries, desc="Progress"):
        metrics = compute_row_metrics(df, country)
        if metrics:
            metrics['Country'] = country
            results.append(metrics)

    if not results:
        print("Warning: No correlation results computed!")
        return pd.DataFrame()

    corr_df = pd.DataFrame(results)

    # Reorder columns
    cols = ['Country', 'Solar', 'Wind', 'Temperature', 'HDD', 'CDD',
            'Dew_Point', 'Wind_Speed', 'Heating_Intensity', 'Cooling_Intensity',
            'Load_Lag_1h', 'Load_Lag_24h', 'Load_Lag_168h', 'Load_Roll_24h',
            'Load_Roll_7d', 'Hour', 'Day_of_Week', 'Is_Weekend', 'Month',
            'Is_Holiday', 'Season']

    # Keep only columns that exist in the results
    cols = [c for c in cols if c in corr_df.columns]
    remaining_cols = [c for c in corr_df.columns if c not in cols]
    cols.extend(remaining_cols)

    return corr_df[cols]

def plot_correlation_heatmap(corr_df, figsize=(18, 14)):
    """
    Create a comprehensive heatmap visualization of the correlation matrix.
    """
    # Prepare data
    plot_df = corr_df.set_index('Country')

    # Create figure
    plt.figure(figsize=figsize)

    # Create heatmap
    ax = sns.heatmap(plot_df,
                     annot=True,
                     cmap='RdBu_r',
                     center=0,
                     fmt=".2f",
                     linewidths=1,
                     linecolor='white',
                     vmin=-1,
                     vmax=1,
                     cbar_kws={'label': 'Correlation Coefficient', 'shrink': 0.8},
                     annot_kws={"size": 8, "weight": "bold"})

    # Style the plot
    ax.xaxis.tick_top()
    ax.xaxis.set_label_position('top')
    plt.xticks(rotation=45, ha='left', fontsize=10)
    plt.yticks(rotation=0, fontsize=10)

    # Add title and labels
    plt.title('European Energy Load Correlation Matrix\nLoad vs Weather, Temporal & Lag Features',
             fontsize=16, pad=40, fontweight='bold')
    plt.xlabel('Features', fontsize=13, labelpad=10)
    plt.ylabel('Country', fontsize=13, labelpad=10)

    # Add grid lines for better readability
    for _, spine in ax.spines.items():
        spine.set_visible(True)
        spine.set_linewidth(1)

    plt.tight_layout()
    plt.show()

    return ax

def plot_feature_group_summary(corr_df, figsize=(16, 10)):
    """
    Create a summary plot showing average correlation by feature group.
    """
    # Define feature groups
    feature_groups = {
        'Weather': ['Solar', 'Wind', 'Temperature', 'Wind_Speed', 'Dew_Point'],
        'Temperature Indices': ['HDD', 'CDD', 'Heating_Intensity', 'Cooling_Intensity'],
        'Load Lags': ['Load_Lag_1h', 'Load_Lag_24h', 'Load_Lag_168h'],
        'Load Rolling': ['Load_Roll_24h', 'Load_Roll_7d'],
        'Temporal': ['Hour', 'Day_of_Week', 'Month', 'Season'],
        'Calendar': ['Is_Weekend', 'Is_Holiday']
    }

    # Calculate mean absolute correlation for each group
    plot_df = corr_df.set_index('Country')
    summary_data = {}

    for group_name, features in feature_groups.items():
        available_features = [f for f in features if f in plot_df.columns]
        if available_features:
            summary_data[group_name] = plot_df[available_features].abs().mean(axis=1)

    summary_df = pd.DataFrame(summary_data)

    # Create heatmap
    plt.figure(figsize=figsize)
    ax = sns.heatmap(summary_df,
                     annot=True,
                     fmt='.3f',
                     cmap='YlOrRd',
                     linewidths=1,
                     linecolor='white',
                     cbar_kws={'label': 'Mean Absolute Correlation', 'shrink': 0.8},
                     annot_kws={"size": 10, "weight": "bold"})

    ax.xaxis.tick_top()
    ax.xaxis.set_label_position('top')
    plt.xticks(rotation=45, ha='left', fontsize=11)
    plt.yticks(rotation=0, fontsize=11)

    plt.title('Feature Group Importance by Country\n(Mean Absolute Correlation with Load)',
             fontsize=16, pad=40, fontweight='bold')
    plt.ylabel('Country', fontsize=13, labelpad=10)

    plt.tight_layout()
    plt.show()

    return ax

# ==================== MAIN EXECUTION ====================

print("=" * 60)
print("EUROPEAN ENERGY LOAD CORRELATION ANALYSIS")
print("=" * 60)

# Use the pre-processed df_hourly dataset
print(f"\nDataset: {df_hourly.shape[0]:,} rows × {df_hourly.shape[1]} columns")
print(f"Countries: {len(countries_with_wind)}")

# Compute correlations
print("\nComputing cross-correlations...")
correlation_matrix = compute_cross_correlation_matrix(df_hourly, countries_with_wind)

if not correlation_matrix.empty:
    print(f"\n✓ Computed correlations for {len(correlation_matrix)} countries")

    # Plot 1: Full correlation heatmap
    print("\n" + "=" * 60)
    print("PLOT 1: Full Correlation Matrix Heatmap")
    print("=" * 60)
    plot_correlation_heatmap(correlation_matrix)

    # Plot 2: Feature group summary
    print("\n" + "=" * 60)
    print("PLOT 2: Feature Group Importance Summary")
    print("=" * 60)
    plot_feature_group_summary(correlation_matrix)

    # Print top correlations for a sample country
    print("\n" + "=" * 60)
    print("TOP CORRELATIONS - SAMPLE COUNTRIES")
    print("=" * 60)

    for country in ['DE', 'FR', 'IT', 'ES']:
        if country in correlation_matrix['Country'].values:
            country_data = correlation_matrix[correlation_matrix['Country'] == country].iloc[0]
            # Get numeric columns only
            num_cols = country_data.index[1:]  # Skip 'Country'
            correlations = pd.to_numeric(country_data[num_cols], errors='coerce')
            top_features = correlations.abs().nlargest(5)

            print(f"\n{country} - Top 5 Features:")
            for feat, corr in top_features.items():
                actual_corr = correlations[feat]
                direction = "→" if actual_corr > 0 else "←"
                print(f"  {feat:20s}: {actual_corr:+.3f} {direction}")

else:
    print("ERROR: No correlation results computed!")

# Multi-Resolution Load Timeline for Germany (DE)
# Uses the real dataset timeline from df_hourly

import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# Ensure datetime index
df_hourly = df_hourly.copy()
df_hourly.index = pd.to_datetime(df_hourly.index)

# Germany load column
country_code = "DE"
load_col = f"{country_code}_load"

# Dataset interval
start_date = df_hourly.index.min()
end_date = df_hourly.index.max()

# Prepare data
df_plot = df_hourly[[load_col]].dropna().sort_index()

# Multi-resolution aggregation
daily_load = df_plot[load_col].resample("D").mean()
weekly_load = df_plot[load_col].resample("W").mean()
monthly_load = df_plot[load_col].resample("M").mean()

# Figure
fig, ax = plt.subplots(figsize=(18, 7))

# Hourly signal
ax.plot(
    df_plot.index,
    df_plot[load_col],
    linewidth=0.35,
    alpha=0.10,
    label="Hourly load"
)

# Daily average
ax.plot(
    daily_load.index,
    daily_load.values,
    linewidth=1.0,
    alpha=0.65,
    label="Daily average"
)

# Weekly average
ax.plot(
    weekly_load.index,
    weekly_load.values,
    linewidth=2.0,
    label="Weekly average"
)

# Monthly average
ax.plot(
    monthly_load.index,
    monthly_load.values,
    linewidth=3.0,
    label="Monthly average"
)

# Titles
ax.set_title(
    "Germany (DE) — Multi-Resolution Electricity Load Timeline",
    fontsize=17,
    fontweight="bold",
    pad=15
)

ax.set_xlabel("Timeline", fontsize=12)
ax.set_ylabel("Electricity Load (MW)", fontsize=12)

# Use real dataset interval
ax.set_xlim(start_date, end_date)

# Timeline formatting based on dataset interval
locator = mdates.AutoDateLocator(minticks=8, maxticks=15)
formatter = mdates.ConciseDateFormatter(locator)

ax.xaxis.set_major_locator(locator)
ax.xaxis.set_major_formatter(formatter)

# Rotate labels
ax.tick_params(axis='x', rotation=45)

# Grid
ax.grid(True, linestyle="--", alpha=0.3)

# Legend
ax.legend(frameon=True)

plt.tight_layout()
plt.show()

# Multi-Resolution Load Timeline for All Countries
# Timeline axis uses the actual time interval from df_hourly

import math
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

# Make sure index is datetime
df_hourly = df_hourly.copy()
df_hourly.index = pd.to_datetime(df_hourly.index)

# Detect load columns
load_cols = [col for col in df_hourly.columns if col.endswith("_load")]
countries = [col.replace("_load", "") for col in load_cols]

n_countries = len(countries)
n_cols = 2
n_rows = math.ceil(n_countries / n_cols)

# Dataset time interval
start_date = df_hourly.index.min()
end_date = df_hourly.index.max()

fig, axes = plt.subplots(
    n_rows,
    n_cols,
    figsize=(22, 5 * n_rows),
    sharex=False
)

axes = axes.flatten()

for ax, country_code in zip(axes, countries):
    load_col = f"{country_code}_load"

    df_plot = df_hourly[[load_col]].dropna().sort_index()

    daily_load = df_plot[load_col].resample("D").mean()
    weekly_load = df_plot[load_col].resample("W").mean()
    monthly_load = df_plot[load_col].resample("M").mean()

    ax.plot(
        df_plot.index,
        df_plot[load_col],
        linewidth=0.35,
        alpha=0.12,
        label="Hourly load"
    )

    ax.plot(
        daily_load.index,
        daily_load.values,
        linewidth=1.0,
        alpha=0.65,
        label="Daily average"
    )

    ax.plot(
        weekly_load.index,
        weekly_load.values,
        linewidth=1.8,
        label="Weekly average"
    )

    ax.plot(
        monthly_load.index,
        monthly_load.values,
        linewidth=2.6,
        label="Monthly average"
    )

    ax.set_title(
        f"{country_code} — Multi-Resolution Load Timeline",
        fontsize=13,
        fontweight="bold"
    )

    ax.set_xlabel("Timeline")
    ax.set_ylabel("Load (MW)")

    # Use real dataset time interval
    ax.set_xlim(start_date, end_date)

    # Automatically choose suitable ticks based on dataset range
    locator = mdates.AutoDateLocator(minticks=5, maxticks=10)
    formatter = mdates.ConciseDateFormatter(locator)

    ax.xaxis.set_major_locator(locator)
    ax.xaxis.set_major_formatter(formatter)

    ax.tick_params(axis="x", rotation=45)
    ax.grid(True, linestyle="--", alpha=0.3)

for ax in axes[n_countries:]:
    ax.remove()

handles, labels = axes[0].get_legend_handles_labels()

fig.legend(
    handles,
    labels,
    loc="upper center",
    ncol=4,
    frameon=True,
    bbox_to_anchor=(0.5, 1.01)
)

fig.suptitle(
    f"Multi-Resolution Electricity Load Timelines Across Countries\n"
    f"Dataset Period: {start_date.date()} to {end_date.date()}",
    fontsize=18,
    fontweight="bold",
    y=1.04
)

plt.tight_layout()
plt.show()

# 15-Day Segment Scatter Plot for ALL Countries
# Legends OUTSIDE each subplot (right side)

import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Detect all load columns
load_cols = [col for col in df_hourly.columns if col.endswith("_load")]

segment_days = 15
n_segments = 24

# Subplot layout
n_countries = len(load_cols)
n_cols = 2
n_rows = math.ceil(n_countries / n_cols)

fig, axes = plt.subplots(
    n_rows,
    n_cols,
    figsize=(24, 5 * n_rows),   # wider figure for outside legends
    sharex=False
)

axes = axes.flatten()

for ax, country_col in zip(axes, load_cols):

    country_name = country_col.replace("_load", "")

    # Prepare data
    df_seg = df_hourly[[country_col]].dropna().copy()
    df_seg = df_seg.sort_index()

    df_seg["year"] = df_seg.index.year
    df_seg["day_of_year"] = df_seg.index.dayofyear

    # Keep first 360 days
    df_seg = df_seg[
        df_seg["day_of_year"] <= segment_days * n_segments
    ]

    # Create segment number
    df_seg["segment"] = (
        (df_seg["day_of_year"] - 1) // segment_days
    ) + 1

    # Mean load per segment
    segment_mean = (
        df_seg
        .groupby(["year", "segment"])[country_col]
        .mean()
        .reset_index()
    )

    # Scatter plot by year
    for year in sorted(segment_mean["year"].unique()):

        data_year = segment_mean[
            segment_mean["year"] == year
        ]

        ax.scatter(
            data_year["segment"],
            data_year[country_col],
            s=50,
            alpha=0.8,
            label=str(year)
        )

    # Titles
    ax.set_title(
        f"Mean Actual Load for {country_name} (15-Day Segments)",
        fontsize=14,
        fontweight="bold"
    )

    # Axis labels
    ax.set_xlabel(
        "15-Day Segment of the Year (1 = Jan 1-15, ..., 24 = Dec 1-15)",
        fontsize=11
    )

    ax.set_ylabel(
        "Mean Actual Load (MW)",
        fontsize=11
    )

    # X-axis formatting
    ax.set_xticks(np.arange(1, 25, 1))
    ax.set_xlim(0.5, 24.5)

    ax.tick_params(
        axis="x",
        labelsize=9
    )

    # Grid
    ax.grid(
        True,
        linestyle="--",
        alpha=0.35
    )

    # Legend OUTSIDE subplot
    ax.legend(
        title="Year",
        loc="center left",
        bbox_to_anchor=(1.02, 0.5),
        fontsize=8,
        title_fontsize=9,
        frameon=True
    )

# Remove unused subplots
for ax in axes[n_countries:]:
    ax.remove()

# Main title
fig.suptitle(
    "Mean Electricity Load Across 15-Day Segments",
    fontsize=18,
    fontweight="bold",
    y=1.02
)

# Spacing for outside legends
plt.tight_layout(rect=[0, 0, 0.93, 1])

plt.show()

# Hour × Weekday Heatmap
# Germany (DE)
# Reveals intraday + weekly behavioral patterns

import pandas as pd
import matplotlib.pyplot as plt

# Ensure datetime index
df_hourly = df_hourly.copy()
df_hourly.index = pd.to_datetime(df_hourly.index)

# Germany load column
country_code = "DE"
load_col = f"{country_code}_load"

# Prepare dataframe
df_heatmap = df_hourly[[load_col]].dropna().copy()

# Extract temporal features
df_heatmap["hour"] = df_heatmap.index.hour
df_heatmap["weekday"] = df_heatmap.index.dayofweek

# Weekday names
weekday_names = {
    0: "Mon",
    1: "Tue",
    2: "Wed",
    3: "Thu",
    4: "Fri",
    5: "Sat",
    6: "Sun"
}

# Average load by weekday and hour
pivot_table = (
    df_heatmap
    .groupby(["weekday", "hour"])[load_col]
    .mean()
    .unstack()
)

# Rename weekday index
pivot_table.index = pivot_table.index.map(weekday_names)

# Plot
fig, ax = plt.subplots(figsize=(14, 5))

im = ax.imshow(
    pivot_table,
    aspect="auto",
    cmap="viridis"
)

# Titles
ax.set_title(
    "Germany (DE) — Hour × Weekday Electricity Load Heatmap",
    fontsize=16,
    fontweight="bold",
    pad=15
)

# Axis labels
ax.set_xlabel("Hour of Day", fontsize=12)
ax.set_ylabel("Day of Week", fontsize=12)

# Ticks
ax.set_xticks(range(24))
ax.set_xticklabels(range(24))

ax.set_yticks(range(7))
ax.set_yticklabels(pivot_table.index)

# Colorbar
cbar = plt.colorbar(im)
cbar.set_label("Average Electricity Load (MW)")

plt.tight_layout()
plt.show()

# Simplified Weather vs Load Plot
# Cleaner and more publication-oriented
# Uses df_hourly from your notebook

import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Detect countries
load_cols = [col for col in df_hourly.columns if col.endswith("_load")]
countries = [col.replace("_load", "") for col in load_cols]

# Layout
n_countries = len(countries)
n_cols = 2
n_rows = math.ceil(n_countries / n_cols)

fig, axes = plt.subplots(
    n_rows,
    n_cols,
    figsize=(18, 4.5 * n_rows)
)

axes = axes.flatten()

for ax, country_code in zip(axes, countries):

    load_col = f"{country_code}_load"
    temp_col = f"{country_code}_temperature"

    if temp_col not in df_hourly.columns:
        ax.set_visible(False)
        continue

    df_plot = df_hourly[[load_col, temp_col]].dropna()

    # Temperature bins
    bins = np.arange(
        np.floor(df_plot[temp_col].min()),
        np.ceil(df_plot[temp_col].max()) + 1,
        1
    )

    df_plot["temp_bin"] = pd.cut(df_plot[temp_col], bins)

    trend = (
        df_plot
        .groupby("temp_bin")[load_col]
        .mean()
    )

    std_dev = (
        df_plot
        .groupby("temp_bin")[load_col]
        .std()
    )

    bin_centers = np.array([
        interval.mid for interval in trend.index.categories
    ])

    # Main trend line
    ax.plot(
        bin_centers,
        trend.values,
        linewidth=3
    )

    # Variability band
    ax.fill_between(
        bin_centers,
        trend.values - std_dev.values,
        trend.values + std_dev.values,
        alpha=0.2
    )

    ax.set_title(
        f"{country_code} — Temperature vs Load",
        fontsize=13,
        fontweight="bold"
    )

    ax.set_xlabel("Temperature (°C)")
    ax.set_ylabel("Load (MW)")

    ax.grid(True, linestyle="--", alpha=0.25)

# Remove unused axes
for ax in axes[n_countries:]:
    ax.remove()

fig.suptitle(
    "Weather–Load Relationships Across European Countries",
    fontsize=18,
    fontweight="bold",
    y=1.02
)

plt.tight_layout()
plt.show()

# Multivariate LSTM Model — Corrected Data Preparation
# Germany (DE)

import numpy as np
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

# -----------------------------
# 1. Select target country
# -----------------------------
country_code = "DE"
target_col = f"{country_code}_load"

df_model = df_hourly.copy()
df_model.index = pd.to_datetime(df_model.index)
df_model = df_model.sort_index()

# -----------------------------
# 2. Create cyclical time features
# -----------------------------
df_model["hour"] = df_model.index.hour
df_model["day_of_week"] = df_model.index.dayofweek
df_model["month"] = df_model.index.month

df_model["hour_sin"] = np.sin(2 * np.pi * df_model["hour"] / 24)
df_model["hour_cos"] = np.cos(2 * np.pi * df_model["hour"] / 24)

df_model["weekday_sin"] = np.sin(2 * np.pi * df_model["day_of_week"] / 7)
df_model["weekday_cos"] = np.cos(2 * np.pi * df_model["day_of_week"] / 7)

df_model["month_sin"] = np.sin(2 * np.pi * df_model["month"] / 12)
df_model["month_cos"] = np.cos(2 * np.pi * df_model["month"] / 12)

df_model["is_weekend"] = df_model["day_of_week"].isin([5, 6]).astype(int)

# -----------------------------
# 3. Select LSTM features
# -----------------------------
candidate_features = [
    target_col,
    f"{country_code}_Load_Lag_1h",
    f"{country_code}_Load_Lag_24h",
    f"{country_code}_Load_Lag_168h",
    f"{country_code}_Load_Roll_24h",
    f"{country_code}_Load_Roll_7d",
    f"{country_code}_Temperature",
    f"{country_code}_HDD",
    f"{country_code}_CDD",
    f"{country_code}_Heating_Intensity",
    f"{country_code}_Cooling_Intensity",
    "hour_sin",
    "hour_cos",
    "weekday_sin",
    "weekday_cos",
    "month_sin",
    "month_cos",
    "is_weekend"
]

features = [col for col in candidate_features if col in df_model.columns]

df_lstm = df_model[features].dropna().copy()

print("Selected features:")
print(features)
print("Dataset shape:", df_lstm.shape)

# -----------------------------
# 4. Train/Test period definition
# -----------------------------
train_start = "2015-01-01"
train_end = "2018-12-31 23:00:00"

test_start = "2019-01-01"
test_end = "2019-12-31 23:00:00"

sequence_length = 168
forecast_horizon = 1

target_index = df_lstm.columns.get_loc(target_col)

# -----------------------------
# 5. Scale using TRAINING DATA ONLY
# -----------------------------
train_data_raw = df_lstm.loc[train_start:train_end]

scaler = MinMaxScaler()
scaler.fit(train_data_raw)

scaled_data = scaler.transform(df_lstm)

scaled_df = pd.DataFrame(
    scaled_data,
    index=df_lstm.index,
    columns=df_lstm.columns
)

# -----------------------------
# 6. Create LSTM sequences
# -----------------------------
X = []
y = []
sequence_dates = []

for i in range(sequence_length, len(scaled_df) - forecast_horizon + 1):
    X.append(scaled_df.iloc[i-sequence_length:i].values)
    y.append(scaled_df.iloc[i + forecast_horizon - 1, target_index])
    sequence_dates.append(scaled_df.index[i + forecast_horizon - 1])

X = np.array(X)
y = np.array(y)
sequence_dates = pd.to_datetime(sequence_dates)

print("X shape:", X.shape)
print("y shape:", y.shape)

# -----------------------------
# 7. Time-based split
# -----------------------------
train_mask = (
    (sequence_dates >= train_start) &
    (sequence_dates <= train_end)
)

test_mask = (
    (sequence_dates >= test_start) &
    (sequence_dates <= test_end)
)

X_train = X[train_mask]
y_train = y[train_mask]

X_test = X[test_mask]
y_test = y[test_mask]

print("Training set:", X_train.shape, y_train.shape)
print("Testing set:", X_test.shape, y_test.shape)

# Multivariate LSTM Architecture
# Next-hour electricity load forecasting

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping, ReduceLROnPlateau

# -----------------------------
# 1. Define input shape
# -----------------------------
n_timesteps = X_train.shape[1]   # 168 hours
n_features = X_train.shape[2]    # number of selected variables

print("Timesteps:", n_timesteps)
print("Features:", n_features)

# -----------------------------
# 2. Build LSTM model
# -----------------------------
model = Sequential([
    LSTM(
        units=64,
        return_sequences=True,
        input_shape=(n_timesteps, n_features)
    ),
    Dropout(0.2),

    LSTM(
        units=32,
        return_sequences=False
    ),
    Dropout(0.2),

    Dense(32, activation="relu"),
    Dense(1)
])

# -----------------------------
# 3. Compile model
# -----------------------------
model.compile(
    optimizer=tf.keras.optimizers.Adam(learning_rate=0.001),
    loss="mse",
    metrics=["mae"]
)

# -----------------------------
# 4. Callbacks
# -----------------------------
early_stop = EarlyStopping(
    monitor="val_loss",
    patience=10,
    restore_best_weights=True
)

reduce_lr = ReduceLROnPlateau(
    monitor="val_loss",
    factor=0.5,
    patience=5,
    min_lr=1e-6
)

# -----------------------------
# 5. Model summary
# -----------------------------
model.summary()

# -----------------------------
# 6. Train LSTM model
# -----------------------------
history = model.fit(
    X_train,
    y_train,
    epochs=50,
    batch_size=64,
    validation_split=0.1,
    callbacks=[early_stop, reduce_lr],
    shuffle=False,
    verbose=1
)

# -----------------------------
# 7. Generate predictions
# -----------------------------
y_pred_scaled = model.predict(X_test)

# -----------------------------
# 8. Inverse scaling
# -----------------------------
# Create empty arrays for inverse transform
dummy_pred = np.zeros((len(y_pred_scaled), len(features)))
dummy_true = np.zeros((len(y_test), len(features)))

# Put predictions into target column
dummy_pred[:, target_index] = y_pred_scaled.flatten()
dummy_true[:, target_index] = y_test.flatten()

# Inverse transform
y_pred = scaler.inverse_transform(dummy_pred)[:, target_index]
y_true = scaler.inverse_transform(dummy_true)[:, target_index]

# -----------------------------
# 9. Evaluation metrics
# -----------------------------
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

mae = mean_absolute_error(y_true, y_pred)
rmse = np.sqrt(mean_squared_error(y_true, y_pred))
r2 = r2_score(y_true, y_pred)

print(f"MAE  : {mae:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"R²   : {r2:.4f}")

# -----------------------------
# 10. Prediction visualization
# -----------------------------
import matplotlib.pyplot as plt

plt.figure(figsize=(18, 6))

plt.plot(
    y_true[:1000],
    label="Actual Load",
    linewidth=2
)

plt.plot(
    y_pred[:1000],
    label="Predicted Load",
    linewidth=2
)

plt.title(
    "Germany (DE) — Actual vs Predicted Electricity Load",
    fontsize=16,
    fontweight="bold"
)

plt.xlabel("Time")
plt.ylabel("Electricity Load (MW)")

plt.legend()
plt.grid(True, linestyle="--", alpha=0.3)

plt.tight_layout()
plt.show()

# Full Forecast Timeline Visualization
# Train period + Forecast period

# Actual full load
actual_full = df_lstm[target_col]

# Prediction dates
test_dates = sequence_dates[test_mask]

# Predicted series
pred_series = pd.Series(
    y_pred,
    index=test_dates
)

plt.figure(figsize=(20, 7))

# Historical actual load (2015–2018)
plt.plot(
    actual_full.loc["2015":"2018"],
    label="Actual Load (Training Period)",
    linewidth=1.5
)

# Actual 2019 load
plt.plot(
    actual_full.loc["2019"],
    label="Actual Load (2019)",
    linewidth=2
)

# Predicted 2019 load
plt.plot(
    pred_series,
    label="Predicted Load (2019)",
    linewidth=2
)

# Vertical split line
plt.axvline(
    pd.Timestamp("2019-01-01"),
    linestyle="--",
    linewidth=2,
    alpha=0.7
)

plt.title(
    "Germany (DE) — Historical and Forecasted Electricity Load",
    fontsize=18,
    fontweight="bold"
)

plt.xlabel("Timeline")
plt.ylabel("Electricity Load (MW)")

plt.legend()
plt.grid(True, linestyle="--", alpha=0.3)

plt.tight_layout()
plt.show()